apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      volumes:
        - name: secret-vol
          emptyDir: {}
      initContainers:
        - name: fetch-secrets
          image: amazon/aws-cli:latest
          volumeMounts:
            - name: secret-vol
              mountPath: /shared
          env:
            - name: AWS_DEFAULT_REGION
              value: "eu-west-1"
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              yum install -y jq > /dev/null
              RAW_SECRET=$(aws secretsmanager get-secret-value --secret-id dev-postgres-credentials --query SecretString --output text)
              DB_PASS=$(echo "$RAW_SECRET" | jq -r .password)

              if [ -z "$DB_PASS" ] || [ "$DB_PASS" = "null" ]; then
                echo "ERROR: Password extraction failed!"
                exit 1
              fi

              echo "export DB_PASS='$DB_PASS'" > /shared/.env
      containers:
        - name: flask-app
          image: 145250404945.dkr.ecr.eu-west-1.amazonaws.com/dev-flask-app:ff91e875151533b1301c448c83ee7958ecbb58d6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secret-vol
              mountPath: /shared
          env:
            - name: DB_USER
              value: "dbadmin"
            - name: DB_NAME
              value: "postgres"
            - name: DB_HOST
              value: "dev-postgres-db.cpsw066wetag.eu-west-1.rds.amazonaws.com"
          command: ["/bin/sh", "-c"]
          args:
            - |-
              set -e
              . /shared/.env
              python /app/seed_db.py || true
              flask run --host=0.0.0.0 --port=80
